name: sulbar_kerja
description: "Sulbar Kerja — Aplikasi Bursa Kerja Digital Provinsi Sulawesi Barat."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.5.0
  pretty_dio_logger: ^1.4.0

  # Auth storage (Keychain / EncryptedSharedPreferences)
  flutter_secure_storage: ^9.2.2

  # File picker (untuk upload CV)
  file_picker: ^8.0.6
  image_picker: ^1.1.2

  # i18n / formatter
  intl: ^0.19.0

  # Env
  flutter_dotenv: ^5.1.0

  # Utils
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Aset / branding (dijalankan manual saat sudah punya ikon PNG)
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/
    - .env

# Launcher icons (jalankan: dart run flutter_launcher_icons)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#0F5CAB"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  remove_alpha_ios: true
  web:
    generate: false

# Native splash (jalankan: dart run flutter_native_splash:create)
flutter_native_splash:
  color: "#0F5CAB"
  image: assets/splash/splash_logo.png
  color_dark: "#0B2544"
  image_dark: assets/splash/splash_logo.png
  android_12:
    color: "#0F5CAB"
    image: assets/splash/splash_logo_android12.png
    color_dark: "#0B2544"
  fullscreen: false
